-- IDENTIFY DUPLICATE ROWS IN THE TABLE ORDERS ARCHIVE\
-- RETURN A CLEAN RESULT WITHOUT ANY DUPLICATES
SELECT * FROM (
	SELECT
		ROW_NUMBER() OVER(PARTITION BY OrderID ORDER BY CreationTime DESC) RN
		,*
	FROM Sales.OrdersArchive
)t 
WHERE RN=1	